### ISSUE TITLE
Audit tutorial code for use of current libraries

### ISSUE THREAD

**Issue by SimonWoolf** [ably/tutorials#47]
I [updated some tutorials](https://github.com/ably/tutorials/issues/39) for ably-js 1 a while back, but clearly I missed some -- e.g. https://github.com/ably/tutorials/blob/publish-subscribe-javascript/example.html uses legacy ably-js.

This is a bit of a PITA because you have to change it in the first commit, rebase all the other commits on top of it, and then go to the docs repo and change all the sha references to the new ones ala https://github.com/ably/docs/commit/97a734179f022af060f282c5a70cf6fbd9bf7473 , and then make sure that the website is deployed with the new tutorial text before github garbage collects the old shas, so the links never stop working.

(Idle thought: wouldn't this be easier if the docs repo pointed to tags, e.g. a `publish-subscribe-javascript-step1` tag etc. rather than shas, so that we don't need to do docs repo prs every time we do this? cc @mattheworiordan )

**Comment by mattheworiordan** [comment]
> (Idle thought: wouldn't this be easier if the docs repo pointed to tags, e.g. a publish-subscribe-javascript-step1 tag etc. rather than shas, so that we don't need to do docs repo prs every time we do this? cc @mattheworiordan )

@SimonWoolf this is what we instruct everyone to do already 👍 
See https://docs.google.com/document/d/1dVip7-1BhDzME1RZhtxTbkQoZSN4StBzpdVR21YNSWA/edit

The only issue is that if someone does not have access to push tags to our repo, it makes it very hard from them to work in this way.

**Comment by SimonWoolf** [comment]
@tomczoink any progress on this? happened to look at the presence tutorial just now, noticed it was still referencing ably.min.js

**Comment by tomczoink** [comment]
This dropped off my list, I'll add it to be done soon, hopefully will have time on Friday for this.

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/docs/pull/677
